# Generated by Django 2.2 on 2019-06-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Platinum', models.CharField(max_length=44)),
                ('suit', models.CharField(max_length=52)),
                ('gold', models.CharField(max_length=60)),
                ('Ordinary', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=22)),
            ],
        ),
    ]
